from __future__ import annotations

import argparse
import json
import subprocess  # nosec B404
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .redlab import Attempt, AttemptResult, RedLabLedger

PROMPTFOO_VERSION = "0.121.19"
PROMPTFOO_PACKAGE = f"promptfoo@{PROMPTFOO_VERSION}"


@dataclass(frozen=True)
class PlinyImportSummary:
    campaign_id: str
    imported: int
    successful: int
    failed: int
    partial: int
    invalid: int
    attempt_ids: tuple[str, ...]


def write_promptfoo_pliny_config(
    path: str | Path,
    *,
    target: str,
    purpose: str,
    num_tests: int = 5,
    inject_var: str = "prompt",
) -> Path:
    if not target.strip():
        raise ValueError("target is required")
    if not purpose.strip():
        raise ValueError("purpose is required")
    if num_tests < 1:
        raise ValueError("num_tests must be at least 1")
    if not inject_var.strip():
        raise ValueError("inject_var is required")

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "# Generated by Agent Prompt Shield Red Lab.",
                "# The Pliny plugin dynamically fetches prompts from L1B3RT4S.",
                "targets:",
                f"  - id: {_yaml_scalar(target)}",
                "redteam:",
                f"  purpose: {_yaml_scalar(purpose)}",
                f"  injectVar: {_yaml_scalar(inject_var)}",
                "  plugins:",
                "    - id: pliny",
                f"      numTests: {num_tests}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return output


def run_promptfoo_pliny(
    *,
    config: str | Path,
    output: str | Path,
    acknowledge_authorization: bool,
    executable: tuple[str, ...] = ("npx", PROMPTFOO_PACKAGE),
) -> subprocess.CompletedProcess[str]:
    if not acknowledge_authorization:
        raise ValueError("explicit authorization acknowledgement is required")
    config_path = Path(config)
    if not config_path.exists():
        raise ValueError(f"config does not exist: {config_path}")
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        *executable,
        "redteam",
        "run",
        "--config",
        str(config_path),
        "--output",
        str(output_path),
        "--no-share",
    ]
    # No shell is used; the executable and Promptfoo version are fixed by default.
    return subprocess.run(  # nosec B603
        command,
        check=True,
        text=True,
        capture_output=True,
    )


def import_promptfoo_results(
    *,
    ledger_path: str | Path,
    campaign_id: str,
    results_path: str | Path,
    parent_attempt_id: str | None = None,
    delivery_channel: str = "promptfoo:pliny",
) -> PlinyImportSummary:
    ledger = RedLabLedger(ledger_path)
    campaign_ids = {item.campaign_id for item in ledger.campaigns()}
    if campaign_id not in campaign_ids:
        raise ValueError(f"unknown campaign_id: {campaign_id}")
    if parent_attempt_id is not None:
        attempt_ids = {item.attempt_id for item in ledger.attempts(campaign_id)}
        if parent_attempt_id not in attempt_ids:
            raise ValueError(f"unknown parent_attempt_id: {parent_attempt_id}")

    path = Path(results_path)
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ValueError(f"could not read Promptfoo results: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Promptfoo results are not valid JSON: {exc.msg}") from exc

    imported: list[Attempt] = []
    for index, row in enumerate(_iter_promptfoo_outputs(payload), start=1):
        prompt = _extract_prompt(row)
        response = _extract_response(row)
        result = _map_result(row)
        metadata = _extract_metadata(row)
        attempt = ledger.record_attempt(
            Attempt(
                campaign_id=campaign_id,
                attack_family="promptfoo:pliny",
                hypothesis=(
                    "A curated Pliny/L1B3RT4S prompt may expose a failure against the "
                    "campaign success criteria."
                ),
                payload=prompt,
                delivery_channel=delivery_channel,
                result=result,
                target_response=response,
                tool_trace=({"promptfoo": metadata, "row_index": index},),
                failure_reason=_failure_reason(row, result),
                lesson="Imported from Promptfoo Pliny evaluation; independently evaluate before confirmation.",
                parent_attempt_id=parent_attempt_id,
            )
        )
        imported.append(attempt)

    if not imported:
        raise ValueError("no Promptfoo evaluation outputs were found")

    return PlinyImportSummary(
        campaign_id=campaign_id,
        imported=len(imported),
        successful=sum(item.result == AttemptResult.SUCCESSFUL for item in imported),
        failed=sum(item.result == AttemptResult.FAILED for item in imported),
        partial=sum(item.result == AttemptResult.PARTIAL for item in imported),
        invalid=sum(item.result == AttemptResult.INVALID for item in imported),
        attempt_ids=tuple(item.attempt_id for item in imported),
    )


def _iter_promptfoo_outputs(payload: Any) -> Iterable[dict[str, Any]]:
    if isinstance(payload, list):
        for item in payload:
            if isinstance(item, dict):
                yield item
        return
    if not isinstance(payload, dict):
        return
    results = payload.get("results")
    if isinstance(results, dict):
        outputs = results.get("outputs")
        if isinstance(outputs, list):
            for item in outputs:
                if isinstance(item, dict):
                    yield item
            return
    outputs = payload.get("outputs")
    if isinstance(outputs, list):
        for item in outputs:
            if isinstance(item, dict):
                yield item


def _extract_prompt(row: dict[str, Any]) -> str:
    candidates = [
        row.get("prompt"),
        row.get("vars", {}).get("prompt") if isinstance(row.get("vars"), dict) else None,
        row.get("testCase", {}).get("vars", {}).get("prompt")
        if isinstance(row.get("testCase"), dict)
        and isinstance(row.get("testCase", {}).get("vars"), dict)
        else None,
        row.get("test", {}).get("vars", {}).get("prompt")
        if isinstance(row.get("test"), dict) and isinstance(row.get("test", {}).get("vars"), dict)
        else None,
    ]
    for value in candidates:
        if isinstance(value, str) and value.strip():
            return value
    return "[Prompt unavailable in exported Promptfoo row]"


def _extract_response(row: dict[str, Any]) -> str:
    response = row.get("response")
    if isinstance(response, dict):
        output = response.get("output")
        if isinstance(output, str):
            return output
        return json.dumps(response, ensure_ascii=False)
    if isinstance(response, str):
        return response
    output = row.get("output")
    if isinstance(output, str):
        return output
    if output is not None:
        return json.dumps(output, ensure_ascii=False)
    return ""


def _map_result(row: dict[str, Any]) -> AttemptResult:
    success = row.get("success")
    if isinstance(success, bool):
        # Promptfoo success means the target passed its assertion. For red-team imports,
        # assertion failure is the potential security finding.
        return AttemptResult.FAILED if success else AttemptResult.SUCCESSFUL
    grading = row.get("gradingResult")
    if isinstance(grading, dict):
        passed = grading.get("pass")
        if isinstance(passed, bool):
            return AttemptResult.FAILED if passed else AttemptResult.SUCCESSFUL
        score = grading.get("score")
        if isinstance(score, (int, float)):
            if score >= 1:
                return AttemptResult.FAILED
            if score > 0:
                return AttemptResult.PARTIAL
            return AttemptResult.SUCCESSFUL
    return AttemptResult.INVALID


def _failure_reason(row: dict[str, Any], result: AttemptResult) -> str:
    if result == AttemptResult.FAILED:
        return "Promptfoo assertions indicate the target handled the Pliny test successfully."
    if result == AttemptResult.SUCCESSFUL:
        return "Promptfoo assertions indicate a potential red-team finding; independent evaluation required."
    if result == AttemptResult.PARTIAL:
        return "Promptfoo produced a partial score; manual review required."
    error = row.get("error")
    return str(error) if error else "Promptfoo result could not be classified automatically."


def _extract_metadata(row: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "provider",
        "promptId",
        "testIdx",
        "latencyMs",
        "score",
        "success",
        "gradingResult",
        "namedScores",
        "metadata",
    )
    return {key: row[key] for key in keys if key in row}


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="agent-redlab-pliny",
        description="Promptfoo Pliny bridge for authorized Red Lab campaigns.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init", help="Generate a Promptfoo config using the Pliny plugin.")
    init.add_argument("--target", required=True)
    init.add_argument("--purpose", required=True)
    init.add_argument("--num-tests", type=int, default=5)
    init.add_argument("--inject-var", default="prompt")
    init.add_argument("--output", default="promptfooconfig.pliny.yaml")

    run = subparsers.add_parser("run", help="Run Promptfoo Pliny against an authorized target.")
    run.add_argument("--config", default="promptfooconfig.pliny.yaml")
    run.add_argument("--output", default="promptfoo-pliny-results.json")
    run.add_argument(
        "--ack-authorized",
        action="store_true",
        help="Confirm that the target is owned by you or explicitly authorized for testing.",
    )

    import_cmd = subparsers.add_parser("import", help="Import Promptfoo JSON into Red Lab.")
    import_cmd.add_argument("--ledger", default=".redlab/ledger.jsonl")
    import_cmd.add_argument("--campaign", required=True)
    import_cmd.add_argument("--results", required=True)
    import_cmd.add_argument("--parent")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.command == "init":
        path = write_promptfoo_pliny_config(
            args.output,
            target=args.target,
            purpose=args.purpose,
            num_tests=args.num_tests,
            inject_var=args.inject_var,
        )
        print(path)
        return 0
    if args.command == "run":
        try:
            completed = run_promptfoo_pliny(
                config=args.config,
                output=args.output,
                acknowledge_authorization=args.ack_authorized,
            )
        except (OSError, ValueError, subprocess.CalledProcessError) as exc:
            parser.error(str(exc))
        if completed.stdout:
            print(completed.stdout, end="")
        if completed.stderr:
            print(completed.stderr, file=__import__("sys").stderr, end="")
        return 0
    if args.command == "import":
        try:
            summary = import_promptfoo_results(
                ledger_path=args.ledger,
                campaign_id=args.campaign,
                results_path=args.results,
                parent_attempt_id=args.parent,
            )
        except ValueError as exc:
            parser.error(str(exc))
        print(json.dumps(summary.__dict__, indent=2))
        return 0
    parser.error(f"unknown command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
